module.exports = [
  'Mathematics',
  'History',
  'Chemistry',
  'Physics',
  'Biology',
  'Cybernetics',
  'Linguistics',
  'Arts',
  'Geology',
  'Architecture',
  'Ballistics',
  'Robotics',
  'Psychology',
  'Computer science',
  'Cryptographic',
  'Metrology',
  'Pedology',
  'Agronomy',
  'Aeronautics',
  'Bionics',
  'Medicine',
  'Philology',
  'Economy',
  'Nanotechnology',
  'Mechanics'
];